sudo: required
language: python
python:
  - "3.6"

before_install:
 - |
   if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|(.txt)'
   then
     echo "Not running CI since code were not changed."
     exit
   fi

before_script:
  - bash test3.sh
  - wget https://raw.githubusercontent.com/shreejoy/OTA/master/device.sh
  - bash device.sh.1
script:
  - pip3 install -r requirements.txt 
  - python3.6 new.py
  
notifications:
  email:
    on_success: never
    on_failure: never

